// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIZ5H62jAWpQK9hOSvoqPu2HYpQ1dd3fk',
    appId: '1:383812763584:web:78746a85d25765951b9225',
    messagingSenderId: '383812763584',
    projectId: 'hello-firebase-1ff83',
    authDomain: 'hello-firebase-1ff83.firebaseapp.com',
    storageBucket: 'hello-firebase-1ff83.appspot.com',
    measurementId: 'G-NDM5FJK85F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbhcdlhEQXOE6NbV_241ZWeC1D6IjR39s',
    appId: '1:383812763584:android:ec19d81823e00e171b9225',
    messagingSenderId: '383812763584',
    projectId: 'hello-firebase-1ff83',
    storageBucket: 'hello-firebase-1ff83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBokNRtJko8pESV64uoPQpxaKdeZVsvnRw',
    appId: '1:383812763584:ios:f499ee4cc4e1f4721b9225',
    messagingSenderId: '383812763584',
    projectId: 'hello-firebase-1ff83',
    storageBucket: 'hello-firebase-1ff83.appspot.com',
    iosBundleId: 'com.example.formValidationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBokNRtJko8pESV64uoPQpxaKdeZVsvnRw',
    appId: '1:383812763584:ios:f8fcfc967e8846ca1b9225',
    messagingSenderId: '383812763584',
    projectId: 'hello-firebase-1ff83',
    storageBucket: 'hello-firebase-1ff83.appspot.com',
    iosBundleId: 'com.example.formValidationTest.RunnerTests',
  );
}
